# setup mergerfs, snapraid, cron jobs first
# then update env to use proper path

version: "2.1"
networks:
  default: host
services:
  environment:
    - STORAGE='/path/to/storage'
# flaresolverr
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped 

# sonarr
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/sonarr-docker/.config/sonarr:/config
      - ${STORAGE}/anime:/anime
      - ${STORAGE}/tv:/tv #optional
      - ${STORAGE}/torrents:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

# radarr
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/radarr-docker/.config/radarr:/config
      - ${STORAGE]/movies:/movies #optional
      - ${STORAGE}/torrents:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

# jackett
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - "RUN_OPTS=<run options here>" #optional
    volumes:
      - /home/jackett-docker/.config/jackett:/config
      - /downloads::ro
    ports:
      - 9117:9117
    restart: unless-stopped

# plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
      - PLEX_DB='/srv/dev-disk-by-/plexmediaserver'
    volumes:
      - ${PLEX_DB}:/config
      - ${STORAGE}:/data
      - /opt/plexcodecs/Codecs:/config/Library/Application Support/Plex Media Server/Codecs
      - /transcode::ro
    restart: unless-stopped

# transmission
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=brenden #optional
      - PASS=password #optional
      - WHITELIST="" #optional
      - PEERPORT=peerport #optional
      - "HOST_WHITELIST=dnsname list" #optional
    volumes:
      - /home/debian-transmission/transmission-daemon:/config
      - ${STORAGE}:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

# tautulli
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PLEX_DB='/srv/dev-disk-by-/plexmediaserver'
    volumes:
      - /home/tautulli-docker/.config/tautulli:/config
      - ${PLEX_DB}/Library/Application Support/Plex Media Server/Logs:/logs
    ports:
      - 8181:8181
    restart: unless-stopped
